name: Spider Check

on:
  schedule:
    - cron: '0 20 * * 0' # 每周一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: npx tsx scripts/spider.mts
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/db.json data/settings.json
          git diff --cached --quiet || git commit -m "rebot(CI): spider check"
          git push
